name: storage-framework
version: '0.2'
summary: Service for accessing cloud-based storage providers.
description: >
  This snap provides a service to access cloud-based storage providers, such as
  OneDrive, Owncloud, Google Drive, or mCloud, plus a client-side API for applications.
  See lp:storage-framework for details on the framework, as well as
  lp:storage-provider-onedrive, lp:storage-provider-webdav, lp:storage-provider-gdrive,
  and lp:mcloud.
grade: devel
confinement: strict

slots:
  storage-framework:
    interface: storage-framework
  # Allow clients access to the client library
  client-libs:
    interface: content
    content: client-libs
    read:
      - $SNAP/lib/storage-framework/client
  # Allow providers access to the provider library
  provider-libs:
    interface: content
    content: provider-libs
    read:
      - $SNAP/lib/storage-framework/provider

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

apps:
  storage-framework-registry:
    command: desktop-launch $SNAP/lib/storage-framework/storage-framework-registry
    plugs:
      - platform
    slots:
      - storage-framework
  storage-provider-owncloud:
    command: snap-launch $SNAP/lib/storage-framework/provider $SNAP/lib/storage-provider-webdav/storage-provider-owncloud
    plugs:
      - platform
      - network
    slots:
      - storage-framework

parts:
  storage-framework:
    plugin: cmake
    configflags:
      - -DSNAP_BUILD=1
    source: .
    after:
      - desktop-ubuntu-app-platform
    organize:
      share/: usr/share/
      lib/libstorage-framework-qt*: lib/storage-framework/client/
      lib/libstorage-framework-provider*: lib/storage-framework/provider/
    filesets:
      binaries:
        - lib/storage-framework/*
        - -lib/pkgconfig
      dbus:
        - usr/share/dbus-1/services/com.canonical.StorageFramework.*
    install: |
      # Make sure we have a mount point for ubuntu-app-platform
      mkdir -p $SNAPCRAFT_PART_INSTALL/ubuntu-app-platform
      # Fix pkgconfig files to point at the parts subtree so
      # the providers will build correctly.
      # TODO: Might be better to add SNAPCRAFT_PART_INSTALL to configflags above
      #       and to then substitute conditionally for the *.pc.in files depending
      #       on whether -DSNAP_BUILD is set or not.
      sed -e "s@-I/include@-I${SNAPCRAFT_PART_INSTALL}/include@" \
          -e "s@-L/lib@-L${SNAPCRAFT_PART_INSTALL}/lib/storage-framework/provider@" \
          -i $SNAPCRAFT_PART_INSTALL/lib/pkgconfig/storage-framework-provider-1.pc
      sed -e "s@-I/include@-I${SNAPCRAFT_PART_INSTALL}/include@" \
          -e "s@-L/lib@-L${SNAPCRAFT_PART_INSTALL}/lib/storage-framework/client@" \
          -i $SNAPCRAFT_PART_INSTALL/lib/pkgconfig/storage-framework-qt-local-client-1.pc
      sed -e "s@-I/include@-I${SNAPCRAFT_PART_INSTALL}/include@" \
          -e "s@-L/lib@-L${SNAPCRAFT_PART_INSTALL}/lib/storage-framework/client@" \
          -i $SNAPCRAFT_PART_INSTALL/lib/pkgconfig/storage-framework-qt-client-1.pc
      sed -e "s@-I/include@-I${SNAPCRAFT_PART_INSTALL}/include@" \
          -e "s@-L/lib@-L${SNAPCRAFT_PART_INSTALL}/lib/storage-framework/client@" \
          -i $SNAPCRAFT_PART_INSTALL/lib/pkgconfig/storage-framework-qt-client-2.pc
    prime:
      - $binaries
      - $dbus
      - ubuntu-app-platform

  # For now, the providers are part of the storage-framework snap. Eventually, they will have to each
  # live inside their own snap.
  storage-provider-owncloud:
    plugin: cmake
    configflags:
      - -DSNAP_BUILD=1
    source: lp:storage-provider-webdav
    #source: ../../storage-provider-webdav/snap-build
    after:
      - storage-framework
    organize:
      share/: usr/share/
    filesets:
      binaries:
        - bin/*
        - lib/storage-provider-webdav/*
      accounts:
        - usr/share/accounts/applications/storage-provider*
      applications:
        - usr/share/applications/storage-provider*
      dbus:
        - usr/share/dbus-1/services/com.canonical.StorageFramework.Provider.*
    prime:
      - $binaries
      - $accounts
      - $applications
      - $dbus

# TODO: Add other providers (OneDrive, Google Drive, mCloud)
